export const TAGS = [
  "🛍️ Marketing",
  "💼 Freelancer",
  "💻 Software",
  "📈 Sales",
  "🎓 Student",
  "🐾 Pet Parents",
  "🍔 Foodie",
  "🎵 Music",
  "🏅 Sports",
  "🌈 LGBTQ+",
  "🎨 Art",
  "🏥 Healthcare",
  "🏦 Finance",
  "📚 Education",
  "🌿 Environment",
  "🔧 Engineering",
  "🎬 Entertainment",
  "🌐 Technology",
  "🏋️‍♀️ Fitness",
  "🚀 Entrepreneur",
  "📸 Photography",
  "🌍 Travel",
  "📘 Book Lover",
  "🎮 Gaming",
  "🌟 Astrology",
];

export const SETTINGS_FIELDS = [
  { fieldName: "firstName", displayName: "First Name" },
  { fieldName: "lastName", displayName: "Last Name" },
  { fieldName: "quote", displayName: "Quote" },
  { fieldName: "location", displayName: "Location" },
  { fieldName: "facebookLink", displayName: "Facebook Account" },
  { fieldName: "instagramLink", displayName: "Instagram Account" },
  { fieldName: "twitterLink", displayName: "Twitter Account" },
  { fieldName: "websiteLink", displayName: "Personal/Business Website" },
  { fieldName: "linkedinLInk", displayName: "LinkedIn Account" },
];
